### PR TITLE
Add replaceRange property to suggestion

### PR DESCRIPTION
**Pull request by nwolverson**
As added to JSON output in 0.9.1

### CODE REVIEW

**Comment by natefaubion** [comment]
So is this a breaking change then?

**Comment by nwolverson** [comment]
Behaviourally, no, this should be optional and so work with the previous 0.8.x compiler output. I believe I tested this but I'm tired so I'll double check that tomorrow...

In terms of psa as a library, of course it would be as the type has changed

**Comment by nwolverson** [comment]
Just checked with psc 0.8.5 again and everything seems fine, json pass-through output shows up

**Comment by natefaubion** [comment]
Since I haven't technically published psa as a library, I don't know if I consider it a breaking change then. I should split out the library part into a separate package from the binary.

**Comment by nwolverson** [comment]
Seems reasonable, I suspect it is just me and @kRITZCREEK using this way just now

**Comment by natefaubion** [comment]
Thanks!

**Comment by natefaubion** [comment]
I had to tweak this because it wasn't quite backwards compatible. If there was a suggestion, but no `replaceRange` property it would break. Do you mind testing master with your use case (I'm still on 0.8.5 and it works correctly now when running `npm test`).

**Pull request merged**
